apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: k8s-demo
  labels:
    app: k8s-demo-backend
spec:
  selector:
    app: k8s-demo-backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
