apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: k8s-demo
  labels:
    app: k8s-demo-frontend
spec:
  selector:
    app: k8s-demo-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
