source ../.venv/bin/activate

manim-slides render main.py ThreeLayerAppScene EvolutionOfDeploymentSlide BareMetalDeployment VirtualMachineDeployment ContainersDeployment VirtualMachineVsContainer ProblemWithContainer KubernetesLogo KubernetesOverview KubernetesHowItWorks KubernetesComponent Demo K8sOnDifferentCloudProviders K8sVersusCloudNativeServices ResourcesUsedInSlides OtherUsefulResources FeedbackForm

manim-slides convert ThreeLayerAppScene EvolutionOfDeploymentSlide BareMetalDeployment VirtualMachineDeployment ContainersDeployment VirtualMachineVsContainer ProblemWithContainer KubernetesLogo KubernetesOverview KubernetesHowItWorks KubernetesComponent Demo K8sOnDifferentCloudProviders K8sVersusCloudNativeServices ResourcesUsedInSlides OtherUsefulResources FeedbackForm final_slide.html --open
